server:
  port: 8868
  servlet:
    session:
      timeout: 60000
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
spring:
  application:
    name: myuploader